name: Deploy to Fly.io

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to the directory containing the fly.toml file'
        required: true
        type: string
    secrets:
      FLY_API_TOKEN:
        description: 'Fly.io API token'
        required: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
        cd web
        flyctl --config ./web/fly.toml deploy --remote-only
