name: GitHub CI

on:
  push:
    # # バージョン指定つきタグがプッシュされた時のみ実行
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        # クロスプラットフォーム・ビルド
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      # Actions の基本設定
      - name: Check out Git repositry
        uses: actions/checkout@master

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      # 依存パッケージのインストール
      - name: Install dependencies
        run: npm install

      # GitHub releases へデプロイ
      - name: Deploy
        env:
          # GITHUB_TOKEN は自動生成されるのでとくに設定は不要
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NPM スクリプト名は 'release' にすることが必須
        run: npm run release
