name: Test
on: [push]

jobs:
  deploy:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Detected changed directories
        id: changed
        run: |
          diff="git diff ${{github.event.before}}..${{github.event.after}} --name-only -- "
          diff+=${extensions}
          diff+=" | grep -E "./{1}" | sed -e 's/\/.*//' | uniq"
          directories=$(eval ${diff})
          dirs=""
          for dir in ${directories} ; do
            echo "${dir}"
            dirs+="${dir} "
          done
          echo "::set-output name=directory::${dirs}"

      - name: Run
        run: |
          for dir in $(echo "${{ steps.changed.outputs.directory }}") ; do
            # もし、dirが"web"なら、web/.github/workflows/deploy-flyio.ymlを実行する
            if [ "${dir}" = "web" ]; then
              echo "web"
            fi

            # もし、dirが"client"なら、client/.github/workflows/electron-builder.ymlを実行する
            if [ "${dir}" = "client" ]; then
              echo "client"
            fi
          done
